version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local


services:
  nginx:
    image: nginx:latest
    ports:
      - 81:80
      - 8080:8080
    volumes:
      # - ./nginx_cofig/status.conf:/etc/nginx/sites-enabled/status.conf
      - ./nginx_cofig/status.conf:/etc/nginx/conf.d/status.conf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus-data:/prometheus #:/prometheus is default for change: --storage.tsdb.path=...
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/config
      - alertmanager-data:/data
    command:
      - "--config.file=/config/alertmanager.yml"
      - "--log.level=debug"
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
      - 9113:9113
    command:
      - "-nginx.scrape-uri=http://nginx:8080/status"
    depends_on:
      - nginx